{{- $workersPerFailureDomain := dict }}

{{- if .Values.failureDomains }}
  {{- $workersNumber := int .Values.workersNumber }}
  {{- $numberOfFailureDomains := len .Values.failureDomains }}
  {{- $base := div $workersNumber $numberOfFailureDomains }}
  {{- $remaining := mod $workersNumber $numberOfFailureDomains }}

  {{- range $index, $failureDomain := .Values.failureDomains }}
    {{- $workers := $base }}
    {{- if lt $index $remaining}}
      {{- $workers = add $workers 1}}
    {{- end }}
    {{- $_ := set $workersPerFailureDomain $failureDomain $workers }}
  {{- end }}
{{- else }}
    {{- $_ := set $workersPerFailureDomain "" .Values.workersNumber }}
{{- end }}

{{- range $failureDomain, $workers := $workersPerFailureDomain }}
{{- if gt (int $workers) 0 }}
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  {{- if $failureDomain }}
  name: {{ include "machinedeployment.name" $ }}-{{ $failureDomain }}
  {{- else }}
  name: {{ include "machinedeployment.name" $ }}
  {{- end }}
spec:
  clusterName: {{ include "cluster.name" $ }}
  replicas: {{ $workers }}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{ include "cluster.name" $ }}
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{ include "cluster.name" $ }}
    spec:
      version: {{ regexReplaceAll "\\+k0s.+$" $.Values.k0s.version ""  | quote }}
      clusterName: {{ include "cluster.name" $ }}
      {{- if $failureDomain }}
      failureDomain: {{ $failureDomain }}
      {{- end }}
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: K0sWorkerConfigTemplate
          name: {{ include "k0sworkerconfigtemplate.name" $ }}
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: OpenStackMachineTemplate
        name: {{ include "openstackmachinetemplate.name" $ }}
{{- end }}
{{- end }}
