{{- $failureDomains := list "" }}
{{- if .Values.failureDomains }}
  {{- $failureDomains = .Values.failureDomains }}
{{- end }}

{{- range $_, $failureDomain := $failureDomains }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  {{- if $failureDomain }}
  name: {{ include "openstackmachinetemplate.name" $ }}-{{ $failureDomain }}
  {{- else }}
  name: {{ include "openstackmachinetemplate.name" $ }}
  {{- end }}
spec:
  template:
    spec:
      flavor: {{ $.Values.flavor  | quote }}
      identityRef:
        name: {{ $.Values.clusterIdentity.name  | quote }}
        region: {{ $.Values.identityRef.region  | quote }}
        cloudName: {{ $.Values.identityRef.cloudName | quote }}
      image:
        filter:
          name: {{ $.Values.image.filter.name  | quote }}
          {{- if $.Values.image.filter.tags }}
          tags:
            {{- range $tag := $.Values.image.filter.tags }}
            - {{ $tag }}
            {{- end }}
          {{- end }}
      {{- if $.Values.ports }}
      ports:
        {{ $.Values.ports | toYaml | nindent 8 }}
      {{- end }}
      {{- if $.Values.rootVolume }}
      rootVolume:
        {{- if $failureDomain }}
        availabilityZone: {{ $failureDomain }}
        {{- end }}
        {{ $.Values.rootVolume | toYaml | nindent 8 }}
      {{- end }}
      {{- if gt (len $.Values.additionalBlockDevices) 0 }}
      additionalBlockDevices:
        {{ $.Values.additionalBlockDevices | toYaml | nindent 8 }}
      {{- end }}
      {{- if gt (len $.Values.securityGroups) 0 }}
      securityGroups:
        {{ $.Values.securityGroups | toYaml | nindent 8 }}
      {{- end }}
      {{- $sshKey := $.Values.sshKeyName | default $.Values.sshPublicKey }}
      {{- if $sshKey }}
      sshKeyName: {{ $sshKey }}
      {{- end }}
      {{- with $.Values.floatingIPPoolRef }}
      floatingIPPoolRef:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
